### ISSUE TITLE
How to change Permission for commands

### ISSUE THREAD

**Issue by Colibri05** [Ufinator/mcplugin-position#1]
I don't know how to change the permission for the /position set command. I want all sever members to be able to set positions without having to make them a Operator. Is this somehow possible or is it just the way it is?

**Comment by msnjdev** [comment]
Hi! You need to have a plugin which controls the permissions. You can use for example Luckperms (https://luckperms.net/) or PermissionEX (if supported).

**Comment by msnjdev** [comment]
I will close this issue. If you have any questions, feel free to create a new one.
